// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"accountId"`
	Book      string    `json:"book"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Instore struct {
	Book      string    `json:"book"`
	Bookcount int64     `json:"bookcount"`
	CreatedAt time.Time `json:"createdAt"`
}